[package]
name = ""
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-bpf = []

[dependencies]
borsh = "0.9.3"
num-derive = "0.3"
num-traits = "0.2"
solana-program = ""
thiserror = "1.0"
# Add additional dependencies Here if needed


[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = ""
solana-sdk = ""
# Add additional dependencies here if needed


[lib]
crate-type = ["cdylib", "lib"]
